name: jpeg_encode
description: A minimalistic JPEG encoder.
version: 1.0.1
homepage: https://github.com/deakjahn/jpeg_encode

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

funding:
  - https://buymeacoffee.com/deakjahn

topics:
  - flutter
  - jpeg
  - jpg